### ISSUE TITLE
Doesn't auto-connect on boot

### ISSUE THREAD

**Issue by greduan** [TrilbyWhite/swifer#6]
I have installed it with [my own PKGBUILD](https://github.com/Greduan/my-aur/blob/master/swifer-git/PKGBUILD) and it's been working great. Certainly the best/lightest solution I've found for wifi.

I just seem to run across one problem. It seems it doesn't auto-connect to the configured wifi connection on boot.

I have enabled the service with `# systemctl enable swifer`. And `systemctl --all` reports it did load:

```
swifer.service    loaded    active   exited    Simpler wifi connector tool
```

Except at boot I gotta run `# swifer auto` manually for it to connect.

Is there anything I'm doing wrong or missing? Or is this a bug? I can provide any extra information you need. :)

**Comment by TrilbyWhite** [comment]
In place of 'exited' it should say 'running'.  What is the output of `systemctl status swifer.service`?  Can the service be started successfully after booting?

**Comment by greduan** [comment]
```
$ systemctl status swifer.service
● swifer.service - Simpler wifi connector tool
   Loaded: loaded (/usr/lib/systemd/system/swifer.service; enabled)
   Active: failed (Result: exit-code) since Sat 2014-11-22 07:12:43 CST; 9h ago
  Process: 335 ExecStart=/usr/bin/swifer auto (code=exited, status=5)
```

So what does `status 5` mean?

Also I tried just now and yes, I can start it afterwards with `systemctl start swifer`. When I did that though, it disconnected me from the internet (by which I mean `ping google.com` returned `ping: unknown host google.com`).

At that point this was the output:

```
$ systemctl status swifer.service
● swifer.service - Simpler wifi connector tool
   Loaded: loaded (/usr/lib/systemd/system/swifer.service; enabled)
   Active: active (running) since Sat 2014-11-22 16:45:01 CST; 40s ago
  Process: 13689 ExecStart=/usr/bin/swifer auto (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/swifer.service
           ├─13810 wpa_supplicant -B -i wlan0 -c /usr/share/swifer/WIFINETWORKNAME
           └─13826 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0
```

Then I ran `sudo swifer auto` and it connected me again and now the status was:

```
$ systemctl status swifer.service
● swifer.service - Simpler wifi connector tool
   Loaded: loaded (/usr/lib/systemd/system/swifer.service; enabled)
   Active: active (exited) since Sat 2014-11-22 16:45:01 CST; 3min 18s ago
  Process: 13689 ExecStart=/usr/bin/swifer auto (code=exited, status=0/SUCCESS)
```

**Comment by TrilbyWhite** [comment]
The return code of 5 means no suitable network was found to connect to.  The rest of the ouput suggests other networking services are running.  Disable any other network services first.

Also can you post the output of the following

```
cat /etc/swifer.conf

ls -l /usr/share/swifer
```

**Comment by greduan** [comment]
```
$ cat /etc/swifer.conf
## /etc/swider.conf
## configuration for swifer wireless connection tool

#INTERFACE = wlan0
#DHCP = dhcpcd
#PRE_UP = /path/to/script-or-file
#POST_UP = /path/to/script-or-file


## All user settings must be above these lines
## Do not modify or remove the [NETWORKS] line below
[NETWORKS]
WIFINETWORKNAME
```

```
$ ls -la /usr/share/swifer
total 12
drwxr-xr-x   2 root root 4096 Nov 20 08:07 ./
drwxr-xr-x 159 root root 4096 Nov 21 11:34 ../
-rw-------   1 root root  125 Nov 20 08:07 WIFINETWORKNAME
```

I double checked and where there is `WIFINETWORKNAME` there is a valid wifi network name and it's also the correct one.

I went through the list and disabled stuff like network manager, connman, and other stuff. I thought I had uninstalled them but I guess not...

Also, I just booted up again and it worked fine this time. However I made sure that everything was in ideal state first, modem on, getting internet, etc.

**Comment by TrilbyWhite** [comment]
So it's working then?

**Comment by greduan** [comment]
I guess. I'll do a couple more boots (one per day) and report back. :)

**Comment by greduan** [comment]
Just booted up today, the conditions were all fine. It started up fine, but it didn't connect. Looks like DHCP(C) got a timeout so it didn't connect. I did `sudo systemctl restart swifer` and it worked though.

Does Swifer have an auto-retry feature? Like after 15 secs it tries to connect again if it previously couldn't?

**Comment by TrilbyWhite** [comment]
Yes.  Edit the service file and comment the current exec line and uncomment one of the ones with "reconnect" in it.  This will try to connect, then stay alive as a daemon process watching /proc/net/wireless - if the connection drops below a threshold of quality (or does not exist) it will reconnect.  This check runs every 10 seconds by default.

This whole mechanism was implemented for another user - and from the bit of feedback I've received, it seems to work.  However, be warned this is a feature I've _never_ used nor tested myself.

Does your modem, router, etc, get restarted every time you start your computer?  You commented before that when these were under 'ideal' conditions swifer works.  What are non-ideal conditions?  If your connection is transient, swifer is probably not the tool for you.  Swifer was never meant as a full management tool - check out network manager for that.  I actually have thought about completely removing the reconnect option as it is really an ugly hack - this is the wrong tool for that behavior.

Swifer is intentionally simple: it merely automates the manual connection steps.  If the manual steps would fail due to your modem not being on, swifer will also fail.

**Comment by greduan** [comment]
> This whole mechanism was implemented for another user - and from the bit of feedback I've received, it seems to work. However, be warned this is a feature I've never used nor tested myself.

All right, I'll provide feedback. :)

> Does your modem, router, etc, get restarted every time you start your computer? You commented before that when these were under 'ideal' conditions swifer works. What are non-ideal conditions?

At my house we turn off the modem whenever we go to sleep, for various reasons. With "ideal" conditions I mean that the modem was on and there is a working internet connection before I turn on my laptop. Non-ideal would be the modem being off, still in the process of turning on, or on but no internet connection being provided by the internet provider.

> If your connection is transient, swifer is probably not the tool for you. Swifer was never meant as a full management tool - check out network manager for that. I actually have thought about completely removing the reconnect option as it is really an ugly hack - this is the wrong tool for that behavior.

The connection isn't transient. But it is what you would call crappy. Randomly Infinitum (only internet provider in México) stops giving you internet, or since they sell way more bandwidth than they have, packets get lost (so the modem considers the connection lost), etc. It's just not 100%.

> Swifer is intentionally simple: it merely automates the manual connection steps.

And that is why I like it. :)

I actually created this issue originally because even though the conditions were "ideal" for some reason Swifer wasn't starting a connection. I suspect that has to do with other network managers that were on (even though I stopped and disabled them). After going through the whole list of services (with `systemctl --all`) and disabling anything that was a network manager it worked fine.

**Comment by TrilbyWhite** [comment]
For clarity, swifer (without the "reconnect" option) will start up the other tools that are daemonized and continue to run (wpa_supplicant as need and dhcpcd).  If your service provider craps out temporarily, there should be no problem: when service comes back your internet will be back as the connection to your router is maintained by dhcpcd.

If, in contrast, your router is not up and broadcasting, swifer has nothing to connect to, so dhcpcd is never successfully backgrounded.  If you frequently turn on the modem/router at the same times as your computer, you may want to just start swifer after booting up and/or add a timer/delay to it.

Although, I suppose I could add a 'delay' option perhaps instead of the reconnect.  This way swifer would continue retrying for a certain amount of time before giving up.  This wouldn't be as ugly as the reconnect hack, so I'll give it some consideration.

EDIT: that was easy.  I just pushed the "wait" option, though I didn't revise the service file.  You can revise the service file to have an exec line `swifer auto wait`.  I haven't tested this yet, but at home I have a similar situation to yours: I often turn on the router as I start up the computer - I often have to restart swifer after boot up if the router takes a minute to get up and running.  So I should also be able to test (and benefit from) this idea - thanks.

**Comment by greduan** [comment]
Awesome! Thanks a ton! :D
I'll try it myself and provide feedback. :)

**Comment by greduan** [comment]
> So I should also be able to test (and benefit from) this idea - thanks.

No problem. :) Thanks for the software you make. :)

**Comment by greduan** [comment]
Just tried it, worked great. :)

**Comment by greduan** [comment]
Just a log I recorded this morning:

```
● swifer.service - Simpler wifi connector tool
   Loaded: loaded (/usr/lib/systemd/system/swifer.service; enabled)
   Active: active (running) since Tue 2014-12-02 08:31:13 CST; 3min 33s ago
  Process: 351 ExecStart=/usr/bin/swifer auto wait (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/swifer.service
           ├─407 wpa_supplicant -B -i wlan0 -c /usr/share/swifer/INFINITUM6D7DED
           └─410 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0 

Dec 02 08:31:37 arch-vostro1500 dhcpcd[398]: wlan0: carrier acquired
Dec 02 08:31:37 arch-vostro1500 dhcpcd[398]: wlan0: carrier acquired
Dec 02 08:31:37 arch-vostro1500 dhcpcd[398]: wlan0: IAID 44:ad:c2:eb
Dec 02 08:31:37 arch-vostro1500 dhcpcd[398]: wlan0: IAID 44:ad:c2:eb
Dec 02 08:31:38 arch-vostro1500 dhcpcd[398]: wlan0: soliciting a DHCP lease
Dec 02 08:31:38 arch-vostro1500 dhcpcd[398]: wlan0: soliciting a DHCP lease
Dec 02 08:31:38 arch-vostro1500 dhcpcd[398]: wlan0: soliciting an IPv6 router
Dec 02 08:31:38 arch-vostro1500 dhcpcd[398]: wlan0: soliciting an IPv6 router
Dec 02 08:31:45 arch-vostro1500 dhcpcd[398]: timed out
Dec 02 08:31:45 arch-vostro1500 dhcpcd[398]: timed out
```

From what I can tell it's been 3 mins since Swifer started but it couldn't get the lease so it stopped completely before 5 minutes were up.

Does it just try to get a lease for 5 mins or does it try to get a successful connection for 5 mins?

**Comment by TrilbyWhite** [comment]
Once dhcpcd is running swifer is gone (unless you also use the reconnect mode, but I wouldnt recommend this, that code will not likely be around long).

The new option was only for swifer to wait until a network is available.  If your router is broadcasting (e.g. the network is available) but not running a dhcp service that has nothing to do with swifer.

In this case swifer successfully connected to the network requested.

**Comment by greduan** [comment]
OK, I see. Not a problem, just wanted to make sure it was intended. I'll just start my computer a couple mins later.

In a week or so I'll be switching to a new internet provider (because of a move) so hopefully their modems don't start broadcasting before they can make leases. lol

**Comment by TrilbyWhite** [comment]
You could also change the timeout for dhcpcd which defaults to 30.

**Comment by greduan** [comment]
OK. It's been working great for a while, and this issue I consider solved. Feel free to close it. :)

**Comment by TrilbyWhite** [comment]
Done.
